ckpt_path: null # used for testing only, add your ckpt path if you want to test the model

model:
  base_learning_rate: 1.0e-04
  target: ldm.models.dino_decoder.DinoDecoder
  params:
    monitor: val/rec_loss
    embed_dim: 32
    lossconfig:
      target: ldm.modules.losses.LPIPSWithDiscriminatorDecoder
      params:
        disc_start: 5001
        disc_weight: 0.5
    ddconfig:
      double_z: true
      z_channels: 392
      resolution: 256
      in_channels: 3
      out_ch: 3
      ch: 128
      ch_mult:
      - 1
      - 1
      - 2
      - 2
      - 4
      num_res_blocks: 2
      attn_resolutions:
      - 16
      dropout: 0.0
    dinoconfig:
      dinov3_location: ..\external_modules\dinov3
      model_name: dinov3_vits16plus
      weights: ..\weight\dinov3\dinov3_vits16plus_pretrain_lvd1689m-4057cbaa.pth
    extra_vit_config:
      output_dim: 8
      mask_ratio: 0.1
      use_outnorm: true

data:
  target: main_svg_autoencoder.DataModuleFromConfig
  params:
    batch_size: 64 # batch size per GPU
    wrap: true
    train:
      target: ldm.data.imagenet.ImageNetTrain
      params:
        data_root: /your_path/ImageNet-1k/
    validation:
      target: ldm.data.imagenet.ImageNetValidation
      params:
        data_root: /your_path/ImageNet-1k/

lightning:
  trainer:
    devices: 8 # number of GPUs, modify it according to your settings
    num_nodes: 1 # number of nodes, modify it according to your settings
    strategy: ddp_find_unused_parameters_true
    accelerator: gpu
    max_epochs: 1000
    precision: 32